/**
 * Temporary mock enrollment service to bypass database issues
 */
export async function getStudentEnrollments(userId: string) {
  console.log("Using mock enrollment data for user:", userId);
  
  const mockEnrollments = [
    {
      id: "mock-enrollment-1",
      userId: userId,
      courseId: "mock-course-1",
      status: "ACTIVE" as const,
      progressPercentage: 75,
      lastAccessedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      completedAt: null,
      totalStudyTime: 480,
      streakDays: 5,
      averageScore: 85.5,
      engagementScore: 0.8,
      lastStreakDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      course: {
        id: "mock-course-1",
        title: "Introduction to Web Development",
        slug: "intro-web-dev",
        tagline: "Learn the fundamentals of web development",
        level: "beginner",
        category: "Web Development",
        instructorId: "mock-instructor-1",
        coverImage: null,
        approvalStatus: "APPROVED" as const,
        publishedAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
        tutorEditingLocked: false,
        draftStructure: null,
        pendingEdit: null,
        hasPendingEdit: false,
        archivedAt: null,
        certificateAvailable: true,
        createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        outcomes: ["HTML", "CSS", "JavaScript"],
        skills: ["Web Development", "Frontend"],
      },
    },
    {
      id: "mock-enrollment-2",
      userId: userId,
      courseId: "mock-course-2",
      status: "ACTIVE" as const,
      progressPercentage: 25,
      lastAccessedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      completedAt: null,
      totalStudyTime: 120,
      streakDays: 3,
      averageScore: 78.0,
      engagementScore: 0.6,
      lastStreakDate: new Date(),
      createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      course: {
        id: "mock-course-2",
        title: "Advanced JavaScript Concepts",
        slug: "advanced-js",
        tagline: "Deep dive into JavaScript advanced topics",
        level: "advanced",
        category: "Programming",
        instructorId: "mock-instructor-2",
        coverImage: null,
        approvalStatus: "APPROVED" as const,
        publishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
        tutorEditingLocked: false,
        draftStructure: null,
        pendingEdit: null,
        hasPendingEdit: false,
        archivedAt: null,
        certificateAvailable: true,
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        outcomes: ["Advanced JavaScript", "ES6+", "Async Programming"],
        skills: ["JavaScript", "Programming", "Advanced Concepts"],
      },
    },
  ];

  return mockEnrollments;
}
