declare module "@prisma/client" {
  // Temporary fallback typings to unblock type-checking during migration.
  // Replace with proper generated Prisma types once tsc issues are resolved.
  export const PrismaClient: any;
  export type PrismaClient = any;

  export namespace Prisma {
    export const PrismaClientKnownRequestError: any;
    export type PrismaClientKnownRequestError = any;
    export type PrismaClientOptions = any;
    export type InputJsonValue = any;
    export type UserGetPayload<T> = any;
    export type JsonValue = any;
    export type ChatThreadInclude = any;
    export type ChatNotificationCreateManyInput = any;
    export type InterviewSessionGetPayload<T = any> = any;
    export type JobOpportunityOrderByWithRelationInput = any;
    export type JobOpportunityUpdateInput = any;
    export type CourseGetPayload<T = any> = any;
    export type CourseOrderByWithRelationInput = any;
    export type NewsUpdateInput = any;
    export type ResumeExperienceUpdateInput = any;
    export type TenantWhereInput = any;
    export type JobAlertUpdateInput = any;
    export type JobOpportunity = any;
    export type CourseUncheckedCreateInput = any;
    export type VolunteerOpportunityWhereInput = any;
    export type ForumThreadGetPayload<T = any> = any;
    export type UserWhereInput = any;
    export type CourseWhereInput = any;
    export type JobOpportunityWhereInput = any;
    export type ResumeUpdateInput = any;
    export type ResumeUpdateInput = any;
    export type UserWhereInput = any;
    export type CourseWhereInput = any;
    export type JobOpportunityWhereInput = any;
    export type ResumeUpdateInput = any;
    export type InterviewFlowStep = any;
    export type InterviewSessionStatus = any;
    export type ExamStatus = any;
    export type ExamType = any;
    export const DbNull: any;
    export const JsonNull: any;
    export const AnyNull: any;
    export type JsonValue = any;
    export type ChatThreadInclude = any;
    export type ChatNotificationCreateManyInput = any;
    export type InterviewSessionGetPayload<T = any> = any;
    export type JobOpportunityOrderByWithRelationInput = any;
    export type JobOpportunityUpdateInput = any;
  }
    export type CourseUncheckedCreateInput = any;
    export type VolunteerOpportunityWhereInput = any;
    export type ForumThreadGetPayload<T = any> = any;
    export type ExamStatus = any;
    export type ExamType = any;

  // Common enums/types used across the codebase — typed as any temporarily.
  export const TenantPlanTier: any;
  export type TenantPlanTier = any;
  export const TenantStatus: any;
  export type TenantStatus = any;
  export const CourseApprovalStatus: any;
  export type CourseApprovalStatus = any;
  export const CourseLevel: any;
  export type CourseLevel = any;
  export const InviteStatus: any;
  export type InviteStatus = any;
  export const JobApplicationStatus: any;
  export type JobApplicationStatus = any;
  export const JobType: any;
  export type JobType = any;
  export const NotificationType: any;
  export type NotificationType = any;
  export const RemoteOption: any;
  export type RemoteOption = any;
  export const Role: any;
  export type Role = any;
  export const UserStatus: any;
  export type UserStatus = any;
  export const TutorApprovalStatus: any;
  export type TutorApprovalStatus = any;
  export const ResumeVisibility: any;
  export type ResumeVisibility = any;
  export const ChatThreadType: any;
  export type ChatThreadType = any;
  export const ResumeExperience: any;
  export type ResumeExperience = any;
  export const ResumeProject: any;
  export type ResumeProject = any;
  export const Resume: any;
  export type Resume = any;
  export const EnrollmentStatus: any;
  export type EnrollmentStatus = any;
  export const LessonFormat: any;
  export type LessonFormat = any;
  export const ResourceType: any;
  export type ResourceType = any;
  export const InterviewFlowStep: any;
  export type InterviewFlowStep = any;
  export const InterviewSessionStatus: any;
  export type InterviewSessionStatus = any;
  export const ChatRole: any;
  export type ChatRole = any;
  export const ChatNotificationType: any;
  export type ChatNotificationType = any;
  export const ExamStatus: any;
  export type ExamStatus = any;
  export const ExamType: any;
  export type ExamType = any;
  export type CourseGetPayload<T = any> = any;
  export type CourseOrderByWithRelationInput = any;
  export type NewsUpdateInput = any;
  export type ResumeExperienceUpdateInput = any;
  export type TenantWhereInput = any;
  export type JobAlertUpdateInput = any;
  export type JobOpportunity = any;
  export type CourseUncheckedCreateInput = any;
  export type VolunteerOpportunityWhereInput = any;
  export type ForumThreadGetPayload<T = any> = any;
  export type JsonValue = any;
  export type CourseOrderByWithRelationInput = any;
  export type CourseGetPayload = any;
  export const ExamStatus: any;
  export type ExamStatus = any;
  export const ExamType: any;
  export type ExamType = any;
}
